# Generated by Django 4.0.5 on 2022-06-04 11:08

from django.db import migrations, models
import django.db.models.deletion
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_classes_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fitness', models.CharField(max_length=15, unique=True)),
                ('muscle', models.CharField(max_length=15, unique=True)),
                ('body_building', models.CharField(max_length=15, unique=True)),
                ('yoga', models.CharField(max_length=15, unique=True)),
                ('advanced', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('desc', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to=mainpage.models.Trainer.get_file_name_trainer)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.types'),
        ),
    ]
