# Generated by Django 4.0.5 on 2022-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_schedule_trainer_types_delete_days_trainer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='desc',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
