# Generated by Django 4.0.5 on 2022-06-04 11:26

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_remove_trainer_facebook_remove_trainer_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(null=True, upload_to=mainpage.models.Trainer.get_file_name_trainer),
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
