# Generated by Django 4.0.5 on 2022-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_schedule_advanced_alter_schedule_body_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
