# Generated by Django 4.0.5 on 2022-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_types_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
