# Generated by Django 4.0.5 on 2022-06-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_alter_types_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day_of_week',
            new_name='class_name',
        ),
    ]
