# Generated by Django 4.0.5 on 2022-06-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_rename_day_of_week_schedule_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='class_name',
            new_name='day_of_week',
        ),
    ]
