# Generated by Django 4.0.5 on 2022-06-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_rename_day_of_week_schedule_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='mainpage.trainer'),
        ),
    ]
