# Generated by Django 4.0.5 on 2022-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_alter_schedule_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
