# Generated by Django 4.0.5 on 2022-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_trainer_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
