# Generated by Django 4.0.5 on 2022-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_name',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
    ]
