# Generated by Django 4.0.5 on 2022-06-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0026_schedule_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('position',)},
        ),
    ]
